### ISSUE TITLE
Errors after update to 3.2.1

### ISSUE THREAD

**Issue by SiskoUrso** [krateng/maloja#270]
I recently updated from 3.1.5 to 3.2.1 , afterwards maloja will no longer load and continues to crash with the following error. Looks like it starts with issue with Last.fm, I am able to roll back to 3.1.5 and everything works correctly again. 

maloja  | [migrations] started
maloja  | [migrations] no migrations found
maloja  | ───────────────────────────────────────
maloja  |   _____ __ __ _____ _____ _____ _____
maloja  |  |     |  |  |   __|_   _|     |     |
maloja  |  |   --|  |  |__   | | | |  |  | | | |
maloja  |  |_____|_____|_____| |_| |_____|_|_|_|
maloja  |        _____ __ __ _ __    ____
maloja  |       | __  |  |  | |  |  |    \
maloja  |       | __ -|  |  | |  |__|  |  |
maloja  |       |_____|_____|_|_____|____/
maloja  |
maloja  |   Based on images from linuxserver.io
maloja  | ───────────────────────────────────────
maloja  |
maloja  | To support LSIO projects visit:
maloja  | https://www.linuxserver.io/donate/
maloja  |
maloja  | ───────────────────────────────────────
maloja  | GID/UID
maloja  | ───────────────────────────────────────
maloja  |
maloja  | User UID:    1000
maloja  | User GID:    1000
maloja  | ───────────────────────────────────────
maloja  |
maloja  | [custom-init] No custom files found, skipping...
maloja  |
maloja  | Maloja is starting!
maloja  | [ls.io-init] done.
maloja  | [lastfm] Error while authenticating with LastFM: AttributeError("'NoneType' object has no attribute 'findtext'")
maloja  | Exception in thread Thread-1 (authorize):
maloja  | Traceback (most recent call last):
maloja  |   File "/usr/lib/python3.10/site-packages/maloja/thirdparty/lastfm.py", line 73, in authorize
maloja  |     self.settings["sk"] = data.find("session").findtext("key")
maloja  | AttributeError: 'NoneType' object has no attribute 'findtext'
maloja  |
maloja  | During handling of the above exception, another exception occurred:
maloja  |
maloja  | Traceback (most recent call last):
maloja  |   File "/usr/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
maloja  |     self.run()
maloja  |   File "/usr/lib/python3.10/threading.py", line 953, in run
maloja  |     self._target(*self._args, **self._kwargs)
maloja  |   File "/usr/lib/python3.10/site-packages/maloja/thirdparty/lastfm.py", line 75, in authorize
maloja  |     log("Error while authenticating with LastFM: " + repr(e))
maloja  |   File "/usr/lib/python3.10/site-packages/doreah/logging.py", line 83, in log
maloja  |     with gopen(logfilename,"a") as logfile:
maloja  |   File "/usr/lib/python3.10/site-packages/doreah/_internal.py", line 39, in gopen
maloja  |     return open(filepath,mode)
maloja  | PermissionError: [Errno 13] Permission denied: '/data/logs/lastfm.log'
maloja  | Traceback (most recent call last):
maloja  |   File "/usr/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 145, in __init__
maloja  |     self._dbapi_connection = engine.raw_connection()
maloja  |   File "/usr/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 3292, in raw_connection
maloja  |     return self.pool.connect()
maloja  |   File "/usr/lib/python3.10/site-packages/sqlalchemy/pool/base.py", line 452, in connect
maloja  |     return _ConnectionFairy._checkout(self)
maloja  |   File "/usr/lib/python3.10/site-packages/sqlalchemy/pool/base.py", line 1269, in _checkout
maloja  |     fairy = _ConnectionRecord.checkout(pool)
maloja  |   File "/usr/lib/python3.10/site-packages/sqlalchemy/pool/base.py", line 716, in checkout
maloja  |     rec = pool._do_get()
maloja  |   File "/usr/lib/python3.10/site-packages/sqlalchemy/pool/impl.py", line 169, in _do_get
maloja  |     with util.safe_reraise():
maloja  |   File "/usr/lib/python3.10/site-packages/sqlalchemy/util/langhelpers.py", line 146, in __exit__
maloja  |     raise exc_value.with_traceback(exc_tb)
maloja  |   File "/usr/lib/python3.10/site-packages/sqlalchemy/pool/impl.py", line 167, in _do_get
maloja  |     return self._create_connection()
maloja  |   File "/usr/lib/python3.10/site-packages/sqlalchemy/pool/base.py", line 393, in _create_connection
maloja  |     return _ConnectionRecord(self)
maloja  |   File "/usr/lib/python3.10/site-packages/sqlalchemy/pool/base.py", line 678, in __init__
maloja  |     self.__connect()
maloja  |   File "/usr/lib/python3.10/site-packages/sqlalchemy/pool/base.py", line 902, in __connect
maloja  |     with util.safe_reraise():
maloja  |   File "/usr/lib/python3.10/site-packages/sqlalchemy/util/langhelpers.py", line 146, in __exit__
maloja  |     raise exc_value.with_traceback(exc_tb)
maloja  |   File "/usr/lib/python3.10/site-packages/sqlalchemy/pool/base.py", line 898, in __connect
maloja  |     self.dbapi_connection = connection = pool._invoke_creator(self)
maloja  |   File "/usr/lib/python3.10/site-packages/sqlalchemy/engine/create.py", line 637, in connect
maloja  |     return dialect.connect(*cargs, **cparams)
maloja  |   File "/usr/lib/python3.10/site-packages/sqlalchemy/engine/default.py", line 616, in connect
maloja  |     return self.loaded_dbapi.connect(*cargs, **cparams)
maloja  | sqlite3.OperationalError: unable to open database file
maloja  |
maloja  | The above exception was the direct cause of the following exception:
maloja  |
maloja  | Traceback (most recent call last):
maloja  |   File "/usr/lib/python3.10/runpy.py", line 187, in _run_module_as_main
maloja  |     mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
maloja  |   File "/usr/lib/python3.10/runpy.py", line 146, in _get_module_details
maloja  |     return _get_module_details(pkg_main_name, error)
maloja  |   File "/usr/lib/python3.10/runpy.py", line 110, in _get_module_details
maloja  |     __import__(pkg_name)
maloja  |   File "/usr/lib/python3.10/site-packages/maloja/__init__.py", line 4, in <module>
maloja  |     from .pkg_global import conf
maloja  |   File "/usr/lib/python3.10/site-packages/maloja/pkg_global/conf.py", line 335, in <module>
maloja  |     from ..database.sqldb import set_maloja_info
maloja  |   File "/usr/lib/python3.10/site-packages/maloja/database/__init__.py", line 17, in <module>
maloja  |     from .. import images
maloja  |   File "/usr/lib/python3.10/site-packages/maloja/images.py", line 69, in <module>
maloja  |     meta.create_all(engine)
maloja  |   File "/usr/lib/python3.10/site-packages/sqlalchemy/sql/schema.py", line 5828, in create_all
maloja  |     bind._run_ddl_visitor(
maloja  |   File "/usr/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 3242, in _run_ddl_visitor
maloja  |     with self.begin() as conn:
maloja  |   File "/usr/lib/python3.10/contextlib.py", line 135, in __enter__
maloja  |     return next(self.gen)
maloja  |   File "/usr/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 3232, in begin
maloja  |     with self.connect() as conn:
maloja  |   File "/usr/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 3268, in connect
maloja  |     return self._connection_cls(self)
maloja  |   File "/usr/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 147, in __init__
maloja  |     Connection._handle_dbapi_exception_noconnection(
maloja  |   File "/usr/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 2430, in _handle_dbapi_exception_noconnection
maloja  |     raise sqlalchemy_exception.with_traceback(exc_info[2]) from e
maloja  |   File "/usr/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 145, in __init__
maloja  |     self._dbapi_connection = engine.raw_connection()
maloja  |   File "/usr/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 3292, in raw_connection
maloja  |     return self.pool.connect()
maloja  |   File "/usr/lib/python3.10/site-packages/sqlalchemy/pool/base.py", line 452, in connect
maloja  |     return _ConnectionFairy._checkout(self)
maloja  |   File "/usr/lib/python3.10/site-packages/sqlalchemy/pool/base.py", line 1269, in _checkout
maloja  |     fairy = _ConnectionRecord.checkout(pool)
maloja  |   File "/usr/lib/python3.10/site-packages/sqlalchemy/pool/base.py", line 716, in checkout
maloja  |     rec = pool._do_get()
maloja  |   File "/usr/lib/python3.10/site-packages/sqlalchemy/pool/impl.py", line 169, in _do_get
maloja  |     with util.safe_reraise():
maloja  |   File "/usr/lib/python3.10/site-packages/sqlalchemy/util/langhelpers.py", line 146, in __exit__
maloja  |     raise exc_value.with_traceback(exc_tb)
maloja  |   File "/usr/lib/python3.10/site-packages/sqlalchemy/pool/impl.py", line 167, in _do_get
maloja  |     return self._create_connection()
maloja  |   File "/usr/lib/python3.10/site-packages/sqlalchemy/pool/base.py", line 393, in _create_connection
maloja  |     return _ConnectionRecord(self)
maloja  |   File "/usr/lib/python3.10/site-packages/sqlalchemy/pool/base.py", line 678, in __init__
maloja  |     self.__connect()
maloja  |   File "/usr/lib/python3.10/site-packages/sqlalchemy/pool/base.py", line 902, in __connect
maloja  |     with util.safe_reraise():
maloja  |   File "/usr/lib/python3.10/site-packages/sqlalchemy/util/langhelpers.py", line 146, in __exit__
maloja  |     raise exc_value.with_traceback(exc_tb)
maloja  |   File "/usr/lib/python3.10/site-packages/sqlalchemy/pool/base.py", line 898, in __connect
maloja  |     self.dbapi_connection = connection = pool._invoke_creator(self)
maloja  |   File "/usr/lib/python3.10/site-packages/sqlalchemy/engine/create.py", line 637, in connect
maloja  |     return dialect.connect(*cargs, **cparams)
maloja  |   File "/usr/lib/python3.10/site-packages/sqlalchemy/engine/default.py", line 616, in connect
maloja  |     return self.loaded_dbapi.connect(*cargs, **cparams)
maloja  | sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) unable to open database file
maloja  | (Background on this error at: https://sqlalche.me/e/20/e3q8)

**Comment by krateng** [comment]
Can you check whether your data folder has correct permissions that it's readable and writable (and for directories, executable) for the user that runs the container?

**Comment by SiskoUrso** [comment]
Yes I have confirmed permissions was correct, even tried changing the data folder to 777 with no change .

**Comment by SiskoUrso** [comment]
I ended up wiping my current data and pulled from a backup and was able to upgrade to 3.2.1 without any issues this time. Closing this issue.
